_wandb:
    value:
        cli_version: 0.24.2
        e:
            d90d69lm3ld2uykcby0htg72njgan7o4:
                args:
                    - projects/configs/StreamPETR/stream_petr_vov_ttc_frozen_20e.py
                    - --work-dir
                    - ./work_dirs/streampetr_ttc_frozen_20e
                    - --launcher
                    - none
                codePath: tools/train.py
                codePathLocal: tools/train.py
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "107307073536"
                        used: "16618971136"
                email: eb408@duke.edu
                executable: /hpc/home/eb408/eb408/CS372/streampetr_env/bin/python
                git:
                    commit: 79462cd82b01cdc12bbaf58b62788b726ba5e8f1
                    remote: https://github.com/eb45/collision-risk-perception.git
                gpu: NVIDIA GeForce RTX 2080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-3e52702f-103f-5f5d-445f-00eda6891ec9
                host: dcc-dhvimdcore-gpu-ferc-s-p15-2
                memory:
                    total: "809642864640"
                os: Linux-5.14.0-611.13.1.el9_7.x86_64-x86_64-with-glibc2.17
                program: tools/train.py
                python: CPython 3.8.20
                root: /hpc/group/naderilab/eb408/CS372/StreamPETR
                slurm:
                    cluster_name: dcc
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: naderilab
                    job_cpus_per_node: "4"
                    job_end_time: "1775844822"
                    job_gid: "1000000"
                    job_gpus: "2"
                    job_id: "45315535"
                    job_name: streampetr_ttc_phase3
                    job_nodelist: dcc-dhvimdcore-gpu-ferc-s-p15-2
                    job_num_nodes: "1"
                    job_partition: common
                    job_qos: normal
                    job_start_time: "1775758422"
                    job_uid: "1512195"
                    job_user: eb408
                    jobid: "45315535"
                    localid: "0"
                    mem_per_node: "32768"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: dcc-dhvimdcore-gpu-ferc-s-p15-2
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /hpc/group/naderilab/eb408/CS372/StreamPETR
                    submit_host: dcc-login-03
                    task_pid: "1044867"
                    tasks_per_node: "1"
                    topology_addr: dcc-dhvimdcore-gpu-ferc-s-p15-2
                    topology_addr_pattern: node
                    tres_per_task: cpu=4
                startedAt: "2026-04-09T18:14:15.982649Z"
                writerId: d90d69lm3ld2uykcby0htg72njgan7o4
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 37
                - 38
                - 41
                - 53
                - 60
            "2":
                - 1
                - 5
                - 37
                - 38
                - 41
                - 53
                - 60
            "3":
                - 61
            "4": 3.8.20
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
