_wandb:
    value:
        cli_version: 0.24.2
        e:
            6e198kqd8afk0vxoq0h91be1lna1qftv:
                args:
                    - projects/configs/StreamPETR/stream_petr_vov_ttc_frozen_20e.py
                    - --seed
                    - "0"
                    - --launcher
                    - pytorch
                    - --work-dir
                    - ./work_dirs/streampetr_ttc_frozen_20e_4gpu
                    - --cfg-options
                    - num_gpus=4
                    - batch_size=2
                    - num_iters_per_epoch=3516
                    - runner.max_iters=70320
                    - checkpoint_config.interval=3516
                    - evaluation.interval=3516
                    - data.train.data_root=/hpc/home/eb408/eb408/CS372/StreamPETR/data_full/nuscenes/
                    - data.train.ann_file=/hpc/home/eb408/eb408/CS372/StreamPETR/data_full/nuscenes/nuscenes2d_temporal_infos_train.pkl
                    - data.val.data_root=/hpc/home/eb408/eb408/CS372/StreamPETR/data_full/nuscenes/
                    - data.val.ann_file=/hpc/home/eb408/eb408/CS372/StreamPETR/data_full/nuscenes/nuscenes2d_temporal_infos_val.pkl
                    - data.test.data_root=/hpc/home/eb408/eb408/CS372/StreamPETR/data_full/nuscenes/
                    - data.test.ann_file=/hpc/home/eb408/eb408/CS372/StreamPETR/data_full/nuscenes/nuscenes2d_temporal_infos_val.pkl
                codePath: tools/train.py
                codePathLocal: tools/train.py
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "107307073536"
                        used: "17211011072"
                email: eb408@duke.edu
                executable: /hpc/home/eb408/eb408/CS372/streampetr_env/bin/python
                git:
                    commit: 09e570a7e3858aecf76433220f6ae5debb192a45
                    remote: https://github.com/eb45/collision-risk-perception.git
                gpu: NVIDIA GeForce RTX 2080 Ti
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-e09bc72e-5555-6726-ed40-2bed9e9f850f
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-825b182c-b59e-7d16-c8ec-6084dc8199b8
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-8de8e67b-289d-a1ae-3745-25f40db81f55
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-27c68d20-a583-d945-3d39-acbc799885c2
                host: dcc-core-ferc-s-z25-21
                memory:
                    total: "403760472064"
                os: Linux-5.14.0-611.13.1.el9_7.x86_64-x86_64-with-glibc2.17
                program: tools/train.py
                python: CPython 3.8.20
                root: /hpc/group/naderilab/eb408/CS372/StreamPETR
                slurm:
                    cluster_name: dcc
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "16"
                    cpus_per_task: "16"
                    gpus_on_node: "4"
                    gtids: "0"
                    job_account: naderilab
                    job_cpus_per_node: "16"
                    job_end_time: "1776265945"
                    job_gid: "1000000"
                    job_gpus: 0,1,2,3
                    job_id: "45514500"
                    job_name: streampetr_ttc_phase3_dist
                    job_nodelist: dcc-core-ferc-s-z25-21
                    job_num_nodes: "1"
                    job_partition: common
                    job_qos: normal
                    job_start_time: "1776179545"
                    job_uid: "1512195"
                    job_user: eb408
                    jobid: "45514500"
                    localid: "0"
                    mem_per_node: "98304"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: dcc-core-ferc-s-z25-21
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /hpc/group/naderilab/eb408/CS372/StreamPETR
                    submit_host: dcc-login-02
                    task_pid: "1338743"
                    tasks_per_node: "1"
                    topology_addr: dcc-core-ferc-s-z25-21
                    topology_addr_pattern: node
                    tres_per_task: cpu=16
                startedAt: "2026-04-14T15:14:28.937800Z"
                writerId: 6e198kqd8afk0vxoq0h91be1lna1qftv
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 37
                - 38
                - 41
                - 53
                - 60
            "2":
                - 1
                - 5
                - 37
                - 38
                - 41
                - 53
                - 60
            "3":
                - 61
            "4": 3.8.20
            "5": 0.24.2
            "8":
                - 2
            "12": 0.24.2
            "13": linux-x86_64
